"""添加缺失的webdav_user_encrypted字段

Revision ID: 7dab97b77eb5
Revises: 8af6b62352f2
Create Date: 2025-06-14 22:03:44.568835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dab97b77eb5'
down_revision = '8af6b62352f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 