"""初始化数据库表结构

Revision ID: 8af6b62352f2
Revises: 
Create Date: 2025-06-14 21:28:37.232240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af6b62352f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('webdav_url_encrypted', sa.Text(), nullable=True),
    sa.Column('webdav_user_encrypted', sa.String(length=255), nullable=True),
    sa.Column('webdav_password_encrypted', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_books_user_id', 'books', ['user_id'], unique=False)
    op.create_index('idx_user_md5', 'books', ['user_id', 'md5'], unique=True)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('chapter', sa.String(length=255), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_page_created', 'highlights', ['book_id', 'page', 'created_time'], unique=True)
    op.create_index('idx_highlights_book_id', 'highlights', ['book_id'], unique=False)
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    op.create_table('reading_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('total_pages_at_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_page_time', 'reading_sessions', ['book_id', 'page', 'start_time'], unique=True)
    op.create_index('idx_sessions_book_id', 'reading_sessions', ['book_id'], unique=False)
    op.create_index('idx_sessions_start_time', 'reading_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_reading_sessions_id'), 'reading_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_sessions_id'), table_name='reading_sessions')
    op.drop_index('idx_sessions_start_time', table_name='reading_sessions')
    op.drop_index('idx_sessions_book_id', table_name='reading_sessions')
    op.drop_index('idx_book_page_time', table_name='reading_sessions')
    op.drop_table('reading_sessions')
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.drop_index('idx_highlights_book_id', table_name='highlights')
    op.drop_index('idx_book_page_created', table_name='highlights')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index('idx_user_md5', table_name='books')
    op.drop_index('idx_books_user_id', table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 